### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by wikijm** [alexrsagen/u2f-test-page#1]
Hi @alexrsagen,

Could you explain how to use your code and your demo page?

For now, I'm able with a [Feitian ePass NFC FIDO U2F Security Key](https://www.amazon.com/Feitian-ePass-NFC-FIDO-Security/dp/B01M1R5LRD/ref=sr_1_2?ie=UTF8&qid=1529753558&sr=8-2&keywords=feitian&dpID=41eY7u7wu8L&preST=_SY300_QL70_&dpSrc=srch) to:

- Fill "Request" by clicking on "GENERATE REQUEST" button
- Click on "Register" button and the autocomplete all fields from first "keyHandle" to "certificate" by clicking on Feitian physical button.

Thanks in advance,
@wikijm

**Comment by alexrsagen** [comment]
When you register the key, it will return a keyHandle, which you may then copy+paste into the keyHandle field above. Once that's filled out, you can click the "Generate Request" button, followed by the "Sign" button to sign the sample request it generates.

That's really all it can do, and all it needs to do. If you're implementing U2F in an application, you may use this page to register keys for testing, etc.

Note that most of the code in this test page is not neccessary for a production implementation of U2F.

**Comment by wikijm** [comment]
OK @alexrsagen,

Thanks for your explaination and your time 🙏

Have a nice day 😃
